CREATE extension if NOT EXISTS "uuid-ossp";

-- DIMENSION TABLES

CREATE table IF NOT EXISTS dim_customers(
	id TEXT PRIMARY KEY NOT NULL,
    type text NOT NULL,
    city text NOT NULL,
    country text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE table IF NOT EXISTS dim_order_status(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE table IF NOT EXISTS dim_payment_method(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE table IF NOT EXISTS dim_currency(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- FACT TABLES
CREATE TABLE IF NOT EXISTS fact_transactions(
	transaction_id text PRIMARY KEY NOT NULL,
	event_type text NOT NULL,
	event_version text NOT NULL,
	event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	customer_id TEXT NOT NULL,
	order_status_id INTEGER NOT NULL,
	order_payment_method_id INTEGER NOT NULL,
	order_currency_id INTEGER NOT NULL,
	order_subtotal NUMERIC NOT NULL,
	order_tax_amount NUMERIC NOT NULL,
	order_shipping_amount NUMERIC NOT NULL,
	order_discount_amount NUMERIC NOT NULL,
	order_total_amount NUMERIC NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES dim_customers(id) ON DELETE CASCADE,
	CONSTRAINT fk_status_id FOREIGN KEY (order_status_id) REFERENCES dim_order_status(id) ON DELETE CASCADE,
	CONSTRAINT fk_payment_method_id FOREIGN KEY (order_payment_method_id) REFERENCES dim_payment_method(id) ON DELETE CASCADE,
	constraint fk_currency_id FOREIGN KEY (order_currency_id) REFERENCES dim_currency(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS fact_transaction_items(
	id TEXT PRIMARY KEY NOT NULL,
	item_id TEXT  NOT NULL,
	transaction_id TEXT NOT NULL,
	event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	category TEXT NOT NULL,
	unit_price NUMERIC NOT NULL,
	quantity NUMERIC NOT NULL,
	discount NUMERIC NOT NULL,
	cost NUMERIC NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_transaction_id FOREIGN KEY (transaction_id) REFERENCES fact_transactions(transaction_id) ON DELETE CASCADE
);
